"""Add grade, area_of_specialization, year_of_graduation, institution, degree, duties_in_last_company to UserProfile table and status to Application table

Revision ID: 2638d80a0abe
Revises: d3df6aea5976
Create Date: 2025-10-19 19:43:30.525659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2638d80a0abe'
down_revision = 'd3df6aea5976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    with op.batch_alter_table('userprofiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('area_of_specialization', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('year_of_graduation', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('institution', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('degree', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('duties_in_last_company', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userprofiles', schema=None) as batch_op:
        batch_op.drop_column('duties_in_last_company')
        batch_op.drop_column('degree')
        batch_op.drop_column('institution')
        batch_op.drop_column('year_of_graduation')
        batch_op.drop_column('area_of_specialization')
        batch_op.drop_column('grade')

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
