"""Set grade, area_of_specialization, year_of_graduation, institution column nullable value in UserProfile table to True

Revision ID: 437942cef0c7
Revises: 5678c8253021
Create Date: 2025-10-20 09:00:27.961322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '437942cef0c7'
down_revision = '5678c8253021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userprofiles', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('area_of_specialization',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('year_of_graduation',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('institution',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('degree',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('duties_in_last_company',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userprofiles', schema=None) as batch_op:
        batch_op.alter_column('duties_in_last_company',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
        batch_op.alter_column('degree',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('institution',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('year_of_graduation',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('area_of_specialization',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('grade',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
