"""Set certification column nullable value in UserProfile table to True

Revision ID: 5678c8253021
Revises: 
Create Date: 2025-10-20 08:57:11.614673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5678c8253021'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userprofiles', schema=None) as batch_op:
        batch_op.alter_column('certification',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('salary_range',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userprofiles', schema=None) as batch_op:
        batch_op.alter_column('salary_range',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('certification',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
