"""Modify UserProfile table to increase length of some columns to accommodate more characters

Revision ID: 68a957c7b9d1
Revises: b0b4169fdf8b
Create Date: 2025-10-26 22:00:05.667244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68a957c7b9d1'
down_revision = 'b0b4169fdf8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userprofiles', schema=None) as batch_op:
        batch_op.alter_column('bio',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=False)
        batch_op.alter_column('about_me',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.String(length=4000),
               existing_nullable=True)
        batch_op.alter_column('duties_in_last_company',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=4000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userprofiles', schema=None) as batch_op:
        batch_op.alter_column('duties_in_last_company',
               existing_type=sa.String(length=4000),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
        batch_op.alter_column('about_me',
               existing_type=sa.String(length=4000),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)
        batch_op.alter_column('bio',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
