"""Differentiate bio and about_me column in UserProfile table

Revision ID: b0b4169fdf8b
Revises: c4d8fc0bc05e
Create Date: 2025-10-20 15:24:33.337862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0b4169fdf8b'
down_revision = 'c4d8fc0bc05e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userprofiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=400), nullable=True))
        batch_op.alter_column('bio',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userprofiles', schema=None) as batch_op:
        batch_op.alter_column('bio',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=400),
               existing_nullable=False)
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
