"""Modify data type for year_end and year_started in UserProfile table

Revision ID: c4d8fc0bc05e
Revises: 2de5b2e19fef
Create Date: 2025-10-20 10:25:15.324600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4d8fc0bc05e'
down_revision = '2de5b2e19fef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userprofiles', schema=None) as batch_op:
        batch_op.alter_column('year_start',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('year_end',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userprofiles', schema=None) as batch_op:
        batch_op.alter_column('year_end',
               existing_type=sa.String(length=10),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('year_start',
               existing_type=sa.String(length=10),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
