"""Add salary_range and certification columns to UserProfile

Revision ID: d3df6aea5976
Revises: 
Create Date: 2025-10-18 12:42:39.888009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3df6aea5976'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userprofiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certification', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('salary_range', sa.String(length=100), nullable=True))

    op.execute("UPDATE userprofiles SET salary_range = 'Not specified' WHERE salary_range IS NULL")
    op.execute("UPDATE userprofiles SET certification = 'None' WHERE certification IS NULL")
    
    with op.batch_alter_table('userprofiles', schema=None) as batch_op:
        batch_op.alter_column('salary_range', existing_type=sa.String(100), nullable=False)
        batch_op.alter_column('certification', existing_type=sa.String(100), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userprofiles', schema=None) as batch_op:
        batch_op.drop_column('salary_range')
        batch_op.drop_column('certification')

    # ### end Alembic commands ###
